apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: accounts-pipeline-run
spec:
  pipelineRef:
    name: accounts-pipeline

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi